### ISSUE TITLE
Calender don't display any entry

### ISSUE THREAD

**Issue by keinereiner** [treolabs/treocrm#19]
If i add a task or meeting, this will not display on the calender.
If i got to the calender and add meeting and task. This will display, if i go to task and back to calender. calender display nothing...
CRM Version: 3.5.5

**Comment by irybachok** [comment]
@keinereiner Please, make sure that the required entities are added to the `Administration > Settings` in the `Calendar Entity List`. If not, select the desired entities from the list and then reload the calendar page. - https://screen.treotest.com/i.rybachok/2019-09-11_14-41-07.jpg

**Comment by keinereiner** [comment]
thanks. it worked.
